#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CogAuth.droid.Resource", IsApplication=true)]

namespace CogAuth.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.AudioRecorder.Resource.String.ApplicationName = global::CogAuth.droid.Resource.String.ApplicationName;
			global::Plugin.AudioRecorder.Resource.String.Hello = global::CogAuth.droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int accent = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int orange = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primary = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int primaryDark = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int window_background = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_filled_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_filled_green = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_filled_orange = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_transparent_white_border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020005
			public const int unicorn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int unicorn_pic = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int wave = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int btnCapture = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int btnNext = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int btn_RegGuidlines_Guidelines = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int btn_RegSuccess_Next = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int btn_RegVoice_Next = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btn_RegVoice_Start = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int btn_RegVoice_play = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int btn_SignInVoice_Next = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int btn_SignInVoice_Play = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int btn_SignInVoice_Record = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int btn_SignIn_Register = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int btn_SignIn_SignIn = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int btn_signInSuccess_Next = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int edt_RegGuidelines_Username = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int imgPhoto = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int txt_RegGuidelines_GuideLines = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Registration_Face = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Registration_Success = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Registration_Voice = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegistrationGuidelines = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SignIn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SignIn_Face = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SignIn_Success = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SignIn_Voice = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int BlueButtonStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int GreenButtonStyle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int OrangeButtonStyle = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int TransparentButtonStyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
